# Generated by Django 4.2.3 on 2023-08-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.CharField(max_length=500)),
                ('response_status', models.IntegerField()),
                ('request_body', models.JSONField(null=True)),
                ('remote_address', models.CharField(max_length=100)),
                ('server_hostname', models.CharField(max_length=200)),
                ('run_time', models.DecimalField(decimal_places=20, max_digits=23)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
