# Generated by Django 4.2.4 on 2023-09-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelTable(
            name='city',
            table='legend_city',
        ),
        migrations.AlterModelTable(
            name='country',
            table='legend_country',
        ),
        migrations.AlterModelTable(
            name='state',
            table='legend_state',
        ),
    ]
