# Generated by Django 4.2.3 on 2023-07-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_admdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admdatetime',
        ),
    ]
