# Generated by Django 4.2.3 on 2023-07-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_student_admdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admdatetime',
            field=models.DateTimeField(null=True),
        ),
    ]
