# Generated by Django 4.2.3 on 2023-07-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_student_admdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admdatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
