# Generated by Django 4.2.3 on 2023-08-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
    ]
