# Generated by Django 4.2.4 on 2023-09-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_excelfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelfile',
            old_name='File',
            new_name='file',
        ),
    ]
